### ISSUE TITLE
CAT scoring

### ISSUE THREAD

**Issue by vmarchman** [langcog/web-cdi#507]
@HenryMehta 

(1) When administering CAT to children over 30 months of age, the output for benchmarks/lookups does not populate in the csv files.  It only populates in the clinical reports.  The benchmark values go to 36 months, so it should be able to do the lookup.

(2) For children who are older than 36 months, I originally got a Server error when I tried to download the clinical report for that individual child.  I just tried again, and the clinical report now gives a blank pdf file.  When I download the csv, I get the output, but the benchmark values are blank.

I think the problem is that there is no "age to compare" in the csv outputs.

**Comment by HenryMehta** [comment]
Hi @vmarchman, I hope the move has gone well.  Do you want me to pick this up asap?

**Comment by vmarchman** [comment]
That would be great - thanks!

**Comment by HenryMehta** [comment]
@vmarchman I've just checked.  The benchmarks only go to 30 months so I've amended the csv downloads so that if child age is greater than max age in benchmark data, then use the max age.  I've deployed this to testing.webcdi.org and tested there and seems to be working to me.  Please check you're happy and let me know and I'll deploy to production.

I've also noticed that if the age is greater than 36 then the administration won't start but errors because we don't have an initial word from CAT.  I could do something about this if you want (eg if age > 36 use initial word for 36 months).  Please let me know if you would like me to do this

**Comment by HenryMehta** [comment]
@vmarchman Actually, I've done an update so if age is greater than 36 the starting word for the administration will be for a child aged 36 months.  Let me know if I need to undo this

**Comment by vmarchman** [comment]
@Henry ***@***.***> Yes - looks great.  Agree that we use the
starting word for 36 months for all kids > 36 months.

Re the lookup percentiles.  For kids > 30 months, the adjusted age to
compare in the clinical report and in the csv outputs should be that max
age, not their chronological age.

But, are there two age ranges?  It goes to 36 months for the theta
percentiles, but only 30 months for the vocab look ups?

**Comment by HenryMehta** [comment]
@vmarchman I think it only going to 30 for both.  I don't have a lookup that goes to 36

**Comment by vmarchman** [comment]
Ok - So then the age to compare is always max = 30 months.

**Comment by HenryMehta** [comment]
@vmarchman Yes, that is right.  I'm not clear.  Are you asking me to change something or is it good as is?

**Comment by vmarchman** [comment]
Hi @Henry ***@***.***> Sorry.  Yes, there should be another column
in the csv output, like for the other forms, representing "age to compare"
or "benchmark age".  It should go right before the percentiles.  For all
children who are between 12 and 36 months, the value in the age and the
benchmark age column will be the same.  But for children > 30 months, the
benchmark age column should be 30 months (since that is the highest age for
the lookup tables) whereas their "age" column reflects their actual,
chronological age.

This value should also go in the clinical reports in the "Age to compare"
box.

Also, the benchmark age should be different in the cases when children have
"adjusted benchmarks" due to prematurity, like we do for the other forms.
Was that set up for the CAT?

**Comment by HenryMehta** [comment]
@vmarchman ok, I'll work through it tomorrow

**Comment by vmarchman** [comment]
Hi @Henry ***@***.***> @George Kachergis
***@***.***>  George is going to give you new lookup tables
for the theta values to 36 months (now only going to 30 months).

So, for the theta percentiles, the age and age to compare would be the same
up to 36 months, and then > 36 months, the age to compare remain 36 months.

For the vocabulary estimates, for kids up to 30 months, the age and age to
compare would be the same.  After 30 months, the vocabulary estimates are
blank (since we don't have vocabulary scores after that age).

We may in the future try to figure out making new vocabulary tables that go
up to 36 months.

Let me know if you have any questions!

-vm

**Comment by HenryMehta** [comment]
@vmarchman 
This will be easier for you to check what I've done with only upto 30 months loaded.

For CAT I've added a new column/field called Benchmark Cohort Age.  This is the age group used in benchmark data.  I have left Age to Compare (which is the age adjusted for being born early/late).  This allows the researcher to know they want to compare the Age to Compare for a certain age, but if we don't have the data they're actually getting a different age and this is it.  I hope that makes sense.

**Comment by vmarchman** [comment]
Hi @Henry ***@***.***>  - Yes I see how that works.  Thanks!

But, let's change the terminology a bit to be more clear.  Let's rename
"Age to Compare" to "Adjusted Age".  We can keep "Benchmark Cohort Age".

Ok, this is how it should work across all forms then.  I just tested the
English WS with a 38 month old kid.  The Age to Compare says 38, but it
should be 30 months and the naming/variables should be parallel to the CAT.

Thanks!!!

Virginia

**Comment by HenryMehta** [comment]
@vmarchman Great.  I've only applied to English CAT at this point.  I'll apply to others over weekend or early next week.  I'm going to be away from Thursday 29th for 1 week so let's try and deploy to production before then

**Comment by HenryMehta** [comment]
@vmarchman all available to test now

**Comment by vmarchman** [comment]
Hi @Henry ***@***.***> I tested CAT and English WG and WS.

CAT seems to be ok.

WG and WS have issues with Adjusted vs. Benchmarking ages.

(1) WG csv is ok, but clinical report has wrong values in Adjusted Age and
Benchmark age.  Not sure what is happening in Adjusted age.

(2) WS Clinical report seems to be ok, but csv has wrong values.  The csv
has Adjusted age = Benchmark age, but it should be same as Chron Age.

Note that for Adjusted Age, the number of weeks premature is subtracted
from the Age (chronological age).   The benchmark age is the same as the
Adjusted age for those children within the age range of the norms (i.e.,
8-18 or 16-30).  So, a child who is 16 months and 8 weeks premature would
have Age = 16, Adjusted Age = 14, and Benchmark age = 14.

If they are *older *than the age range and premature, the adjusted age is
the same as the chron age minus # of weeks premature, but the benchmark age
is the oldest possible.  That is, don't subtract the number of months to
adjust from the oldest age in those cases.  So, a child who is 36 weeks old
and 8 weeks premature, would have Age = 36, Adjusted age = 34, and
Benchmark age = 30.

I can do some more testing tomorrow!

-vm

**Comment by HenryMehta** [comment]
@vmarchman 
I was about to type that your numbers make no sense and then I realised they are weeks and months and the premature is currently treated the same as the age.  

I'm not sure how clinical reports could be ok because the clinical reports were calculating the adjusted age incorrectly.  I was adding/subtracting the number of weeks (rather than months).  I have corrected for CAT, WS and WG.

I do not think you're right on point 2.  If you want benchmarks for the adjusted age, then you want to use the benchmark cohort for that age so if we have a benchmark for that age group we should use it.  If you want benchmarks for the birth age then you select the other csv report and get benchmarks for the chronological age.  This is what my test reports are showing.  If you're getting something different could you let me know the study so I can look at the results you're getting.

I am loading the adjusted age correction for all clinical reports now

**Comment by vmarchman** [comment]
Hi @Henry ***@***.***> Ok, I see what you mean.   But, let's take
this one test case that I've been using.

For a WS child, age = 34 and the child is 8 weeks (2 months) premature.

For the regular Clinical Report and csv, the child's age = 34 and the
child's benchmark age is 30 months.  CORRECT.  We are not correcting for
prematurity in this case.

But, for reports with adjusted benchmarks:

For the clinical report, the age (34) and benchmark age (30) are Correct.
But, the adjusted age is reported as 36, i.e., 2 months older than the
Chronological age.  It should be 32, i.e., 2 months *younger*, 34 months -
8 weeks (2 months) premature.

For the CSV, the adjusted age is reported as 28 (different than in the
clinical report).  This is two months younger than the *Benchmark *age,
rather than 2 months younger than the *chronological *age.

****
I also tested the CAT with a similar aged and premature child.  The
Adjusted age in the CR is 2 months OLDER (rather than younger) than the
chron age.  The adjusted age in the csv is the same as the chron, so not
adjusted at all.

-vm

**Comment by HenryMehta** [comment]
@vmarchman 

**For not CAT administrations**
It looks like we've been calculating Adjusted Age incorrectly for all existing administrations.  The issue only occurs if the Benchmark Cohort Age is lower than the administration age, in which case the Adjusted Age is adjusted from the Benchmark Cohort Age rather than the administration age.  I have corrected this issue and reapplied in test to your administrations.  Please check and confirm.  I am concerned the recalc ran too quickly so if it hasn't worked, please create a new administration with the same test you had above and see if that works.

If this has worked I'll have to update the Summary data for all existing administrations in production.

**For CAT administrations**
I have corrected the way the Adjusted Age is calculated.  It should now be correct

**Comment by vmarchman** [comment]
Hi @Henry ***@***.***> I did some more testing and we're getting
closer, but still not there.

ok - for a CAT administration.  I have a 23 monther who is 8 weeks
premature.  In the csv, his adjusted age is still 23 and so is his
benchmark age - both should be 21.  In the clinical report for that child,
the adjusted age is correct (21), but the benchmark age is still 23.

It was a new administration.

For a non-CAT (WS kid) in the same sort of situation, it is correct in both
the csv and in the clinical report.

I've put screen shots in slack.

The other thing that seems to be happening (somewhat randomly,
unfortunately), is that I enter in the demographics 8 weeks early, and in
the csv, sometimes, it reverts to 7 weeks...?

-vm

**Comment by HenryMehta** [comment]
@vmarchman I am travelling tomorrow so will try and look at this either tonight, Friday or over the weekend.  I think the 7/8 weeks premature is likely to be the mouse moving or you hitting the down arrow by mistake and causing the number to scroll

**Comment by vmarchman** [comment]
@Henry ***@***.***> ok - safe travels!

**Comment by HenryMehta** [comment]
@vmarchman Sorry for the week's delay in doing this but I have now made the amendments, tested locally  and deployed

**Comment by vmarchman** [comment]
No worries @Henry ***@***.***>

I've tested the CAT and they seem good.

We still have issues with the WS and WG though.

On the WS, I have a participant who is 25 months with an adjusted age of 24
months.  The benchmarking age should be 24 months.  It is correct on the
clinical report, but not the csv.

On the WG, the clinical reports are correct, but in the adjusted
benchmarking csvs, the benchmarking age is not the adjusted age, but rather
the chron age.  Adjusted age is correct, but the benchmarking age is not.

Let me know if you want to see examples!

-vm

**Comment by HenryMehta** [comment]
@vmarchman I have deployed a fix.  It needs the summary scores to update to work and I've set yours to update in a couple of minutes but the might take 30 to complete. If they don't you may need to create the criteria for the test again

**Comment by vmarchman** [comment]
@Henry ***@***.***>

 I think it's right!

for English WG, WS, and CAT.

I suddenly think I need to test for Spanish too?  and all the other forms???

**Comment by HenryMehta** [comment]
@vmarchman The calculations are the same for the other forms, certainly for WS and WG.  It would be worth testing Spanish CAT since it does use a different html file.

**Comment by vmarchman** [comment]
Hi @Henry ***@***.***> Mexican CAT looks good!

The only thing is on the clinical reports, it should have simply
"Jackson-Maldonado et al (2003)" on the bottom - not 3rd Edition.

We are good to go!!

(Thanks - I know this was a pain.)

**Comment by HenryMehta** [comment]
@vmarchman Updates now completed.  Everything should work in production

**Comment by vmarchman** [comment]
Thanks @Henry ***@***.***> !
